// Mock data for testing the Racing Roundup website
import { Article } from '../types';

export const mockArticles: Article[] = [
  {
    _id: '1',
    title: 'Hamilton Secures Pole Position at British Grand Prix',
    description: 'Lewis Hamilton delivered a stunning lap to secure pole position for the British Grand Prix, beating Max Verstappen by just 0.023 seconds in a thrilling qualifying session at Silverstone.',
    link: 'https://example.com/f1/hamilton-pole-british-gp',
    pubDate: new Date(2025, 3, 2, 15, 30, 0).toISOString(),
    source: 'F1 News',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=1',
    createdAt: new Date(2025, 3, 2, 15, 35, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 15, 35, 0).toISOString(),
  },
  {
    _id: '2',
    title: 'Ferrari Unveils Major Upgrade Package for Italian Grand Prix',
    description: 'Ferrari has unveiled a comprehensive upgrade package for their home race at Monza, featuring a redesigned floor, new rear wing, and modified sidepods aimed at improving downforce and reducing drag.',
    link: 'https://example.com/f1/ferrari-upgrades-italian-gp',
    pubDate: new Date(2025, 3, 2, 14, 15, 0).toISOString(),
    source: 'Autosport',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=2',
    createdAt: new Date(2025, 3, 2, 14, 20, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 14, 20, 0).toISOString(),
  },
  {
    _id: '3',
    title: 'Bagnaia Dominates MotoGP Practice Sessions at Jerez',
    description: 'Ducati rider Francesco Bagnaia dominated both practice sessions at the Spanish Grand Prix in Jerez, setting a new lap record and showing impressive race pace ahead of qualifying.',
    link: 'https://example.com/motogp/bagnaia-dominates-jerez',
    pubDate: new Date(2025, 3, 2, 13, 45, 0).toISOString(),
    source: 'MotoGP.com',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=3',
    createdAt: new Date(2025, 3, 2, 13, 50, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 13, 50, 0).toISOString(),
  },
  {
    _id: '4',
    title: 'Marc Marquez Signs Two-Year Contract Extension with Honda',
    description: 'Six-time MotoGP champion Marc Marquez has signed a two-year contract extension with Repsol Honda, ending speculation about a potential move to Ducati for the 2026 season.',
    link: 'https://example.com/motogp/marquez-honda-extension',
    pubDate: new Date(2025, 3, 2, 12, 30, 0).toISOString(),
    source: 'Crash.net',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=4',
    createdAt: new Date(2025, 3, 2, 12, 35, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 12, 35, 0).toISOString(),
  },
  {
    _id: '5',
    title: 'Red Bull Racing Announces New Technical Partnership',
    description: 'Red Bull Racing has announced a new technical partnership with a leading aerospace company, bringing cutting-edge materials and aerodynamic expertise to their Formula 1 operation.',
    link: 'https://example.com/f1/red-bull-technical-partnership',
    pubDate: new Date(2025, 3, 2, 11, 15, 0).toISOString(),
    source: 'Formula1.com',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=5',
    createdAt: new Date(2025, 3, 2, 11, 20, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 11, 20, 0).toISOString(),
  },
  {
    _id: '6',
    title: 'Quartararo Frustrated with Yamaha Development Pace',
    description: 'Former MotoGP champion Fabio Quartararo has expressed frustration with the pace of Yamaha\'s development, claiming the 2025 bike has not made the progress needed to challenge for race wins.',
    link: 'https://example.com/motogp/quartararo-yamaha-frustration',
    pubDate: new Date(2025, 3, 2, 10, 0, 0).toISOString(),
    source: 'MCN',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=6',
    createdAt: new Date(2025, 3, 2, 10, 5, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 10, 5, 0).toISOString(),
  },
  {
    _id: '7',
    title: 'McLaren Confirms Driver Lineup for 2026 Season',
    description: 'McLaren has confirmed its driver lineup for the 2026 Formula 1 season, with Lando Norris extending his contract and a promising young talent joining the team from their junior programme.',
    link: 'https://example.com/f1/mclaren-2026-lineup',
    pubDate: new Date(2025, 3, 2, 9, 30, 0).toISOString(),
    source: 'BBC Sport',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=7',
    createdAt: new Date(2025, 3, 2, 9, 35, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 9, 35, 0).toISOString(),
  },
  {
    _id: '8',
    title: 'MotoGP Announces New Race in India for 2026 Season',
    description: 'MotoGP has announced the addition of a new race in India for the 2026 season, with the Buddh International Circuit set to host the inaugural Indian Grand Prix in April 2026.',
    link: 'https://example.com/motogp/india-gp-2026',
    pubDate: new Date(2025, 3, 2, 8, 45, 0).toISOString(),
    source: 'MotoGP.com',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=8',
    createdAt: new Date(2025, 3, 2, 8, 50, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 8, 50, 0).toISOString(),
  },
  {
    _id: '9',
    title: 'Formula 1 Introduces New Sustainability Initiatives',
    description: 'Formula 1 has unveiled a series of new sustainability initiatives aimed at achieving carbon neutrality by 2030, including increased use of biofuels and stricter regulations on team operations.',
    link: 'https://example.com/f1/sustainability-initiatives',
    pubDate: new Date(2025, 3, 2, 7, 15, 0).toISOString(),
    source: 'Autosport',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=9',
    createdAt: new Date(2025, 3, 2, 7, 20, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 7, 20, 0).toISOString(),
  },
  {
    _id: '10',
    title: 'Ducati Dominance Continues in MotoGP Pre-Season Testing',
    description: 'Ducati\'s dominance in MotoGP has continued during pre-season testing, with their factory and satellite teams occupying the top five positions on the combined timesheets at Sepang.',
    link: 'https://example.com/motogp/ducati-preseason-testing',
    pubDate: new Date(2025, 3, 2, 6, 30, 0).toISOString(),
    source: 'Crash.net',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=10',
    createdAt: new Date(2025, 3, 2, 6, 35, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 6, 35, 0).toISOString(),
  },
  {
    _id: '11',
    title: 'Alpine F1 Team Unveils Radical Car Design for Mid-Season',
    description: 'The Alpine Formula 1 team has unveiled a radical redesign of their 2025 car for the mid-season, featuring an innovative sidepod concept and completely revised cooling system.',
    link: 'https://example.com/f1/alpine-radical-redesign',
    pubDate: new Date(2025, 3, 2, 5, 45, 0).toISOString(),
    source: 'F1 News',
    category: 'F1',
    imageUrl: 'https://picsum.photos/800/450?random=11',
    createdAt: new Date(2025, 3, 2, 5, 50, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 5, 50, 0).toISOString(),
  },
  {
    _id: '12',
    title: 'Jorge Martin Leads Championship After Dramatic Portuguese GP',
    description: 'Pramac Ducati rider Jorge Martin has taken the lead in the MotoGP championship after a dramatic Portuguese Grand Prix that saw several title contenders crash out in challenging conditions.',
    link: 'https://example.com/motogp/martin-leads-championship',
    pubDate: new Date(2025, 3, 2, 4, 30, 0).toISOString(),
    source: 'MotoGP.com',
    category: 'MotoGP',
    imageUrl: 'https://picsum.photos/800/450?random=12',
    createdAt: new Date(2025, 3, 2, 4, 35, 0).toISOString(),
    updatedAt: new Date(2025, 3, 2, 4, 35, 0).toISOString(),
  },
];

export const getArticlesByCategory = (category?: string) => {
  if (!category) return mockArticles;
  return mockArticles.filter(article => 
    article.category.toLowerCase() === category.toLowerCase()
  );
};

export const getArticleById = (id: string) => {
  return mockArticles.find(article => article._id === id);
};
